// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKLRf-A5LNCcf3RxWDZ4a_GrV5leV-P3k',
    appId: '1:657105383521:android:95e0c8a21598fd70b27a20',
    messagingSenderId: '657105383521',
    projectId: 'tripadvisor-94f8f',
    storageBucket: 'tripadvisor-94f8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8AAmYnFlV8iB90_TOMyxZ41Mkj5fvS1o',
    appId: '1:657105383521:ios:0ca19361e6b05d33b27a20',
    messagingSenderId: '657105383521',
    projectId: 'tripadvisor-94f8f',
    storageBucket: 'tripadvisor-94f8f.appspot.com',
    androidClientId: '657105383521-oe24p64n6v5sa691j2695120jh6kep11.apps.googleusercontent.com',
    iosClientId: '657105383521-1jfno22re1h105n47chabmm1keired40.apps.googleusercontent.com',
    iosBundleId: 'com.bunab.tripadvisor',
  );

}